spring.application.name=investor-platform
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/investor-platform?charSet=UTF-8
spring.datasource.username = postgres
spring.datasource.password = Ujala@28
spring.datasource.driver-class-name= org.postgresql.Driver
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
logging.level.root=INFO
logging.level.com.wealth.investor=DEBUG
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
